### ISSUE TITLE
Bug with the adding keys mode

### ISSUE THREAD

**Issue by The-Chacal** [Rainbox-dev/DuAEF_Duik#678] opened 2020-05-08 13:34 UTC
**Describe the bug**
When I use the adding keys mode of the animation panel, it add markers instead of keys on the selected property

**To Reproduce**
1. select your position property (or scale or any really)
2. click on the type of key you want to add

**System (please complete the following information):**
 - OS: Windows 10 
 - Version of After Effects: 17.0.6
 - Version of Duik: 16.2.10

**Comment by Nico-Duduf** [comment] 2020-05-14 10:40
Thanks for your feedback, I'll test (and fix) that ASAP

**Comment by Nico-Duduf** [comment] 2020-05-14 15:03
I can't reproduce the issue here.

I have found an issue with the option to add only on selected/all layers, but I can't reproduce your specific one

Could you make a video capture or send me the aep?

**Comment by Nico-Duduf** [comment] 2020-05-14 15:16
OOOOHHH I've understood!

Nevermind! Will be fixed in 16.2.11 ;)

**Comment by Nico-Duduf** [comment] 2020-05-14 15:23
fixed

**Closed by Nico-Duduf** 2020-05-14 15:23 UTC
Labels: Bug, Question
