### ISSUE TITLE
Unable to execute script at line 2514 in AE2020!

### ISSUE THREAD

**Issue by trung031313** [Rainbox-dev/DuAEF_Duik#581] opened 2019-11-14 04:39 UTC
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number: 2475
Error message: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/57741333/68827076-6c1e1b80-06d3-11ea-9a16-b4018d913424.png)

**System (please complete the following information):**
 - OS: 
 - Version of After Effects:  AEcc2020
 - Version of Duik: 16.2.1

**Additional context**

**Comment by Nico-Duduf** [comment] 2019-11-14 16:57
When does this error happens?
When you launch duik, when using a specific tool?

Can you try this: https://duik-docs.rainboxlab.org/install-duik.html#fix-uninstall-duik

**Comment by anatoliepoghirca** [comment] 2019-11-19 06:42
it doesn't work, I still see this error. the script is working though but I am not sure if all the function works ok. Hope you can find what is causing this error. Thank you!

**Comment by Nico-Duduf** [comment] 2019-11-19 07:27
Please answer my questions, when does this happen, were you using one of the tool, switching panel, or at launch?

Also, what is the language you're using for Duik, English or something else?

Have you tried the procedure I've linked above?

**Comment by anatoliepoghirca** [comment] 2019-11-19 07:29
it appears at launch, English.
yes I tried that clean install and it doesn't work unfortunately

**Comment by Nico-Duduf** [comment] 2019-11-19 08:12
Ok thanks!

Do you have the javascript debugger activated (in the script & expressions settings of Fater Effects)?
In this cas turning it off should hide the error.

I'm investigating the issue

**Comment by Nico-Duduf** [comment] 2019-11-24 11:20
I've just released 16.2.2, can anyone try this new version and see if the issue is still there?
Thanks!

**Comment by anatoliepoghirca** [comment] 2019-11-24 12:36
a different error appears now:

![Screenshot_2](https://user-images.githubusercontent.com/57935310/69494743-caaf7a80-0ec7-11ea-8da0-47a29725cced.jpg)

**Comment by Nico-Duduf** [comment] 2019-11-25 13:36
yes it's the same... And I still have no clue about what's going on; I'll have to take some time on this ASAP

**Comment by Nico-Duduf** [comment] 2019-11-25 13:37
I'm kind of disappointed it's not line 2501 though
:)

**Comment by ajf311** [comment] 2019-12-11 16:12
<img width="606" alt="Screen Shot 2019-12-10 at 4 24 16 PM" src="https://user-images.githubusercontent.com/58782814/70638404-d2c92300-1c06-11ea-8ccf-3a0b4176f7c7.png">

- OS: Mojave v10.14.5

- AE: v17.0.1

- Duik: v16.2.2

**Comment by Nico-Duduf** [comment] 2019-12-13 07:09
fixed

**Comment by anatoliepoghirca** [comment] 2019-12-13 10:35
![image](https://user-images.githubusercontent.com/57935310/70793871-03df5a00-1da5-11ea-8cde-4d042de8abe3.png)

**Comment by Nico-Duduf** [comment] 2019-12-13 11:15
Do you have javascript debugging activated?
If so, deactivating it should hide the error.

**Comment by anatoliepoghirca** [comment] 2019-12-13 11:30
is deactivated 
![image](https://user-images.githubusercontent.com/57935310/70797243-c7176100-1dac-11ea-90e0-e949ed155a0e.png)

**Comment by ajf311** [comment] 2019-12-13 17:02
<img width="440" alt="Screen Shot 2019-12-13 at 11 52 24 AM" src="https://user-images.githubusercontent.com/58782814/70817692-173bf680-1da0-11ea-8942-efc69b02118a.png">

OS: Mojave v10.14.5

AE: v17.0.1

Duik: v16.2.2

Looks like it changed from line 2514 to 2515 for me.  I have js debugging disabled.  Duik toolset works fine, just have the pop up when opening.

**Comment by Nico-Duduf** [comment] 2019-12-16 10:02
I know what's going on... finally ;)
Will be fixed in 16.2.4

**Closed** 2020-01-03 15:13 UTC
Labels: Bug, WIP

**Comment by faruk2255** [comment] 2025-07-24 07:15
curTimer=time-thisLayer.inPoint;
speed=effect("Speed")("ADBE Slider Control-0001");
enableCursor=effect("Show Cursor")("ADBE Checkbox Control-0001").value;
cursorChar="|";
T=curTimer*speed;
mumChars=Math.round(T);
if (enableCursor) {
blinkSpeed= 1;//
cursorVisible=Math.round(time*blinkSpeed)%2=0;
cursor=cursorVisible?cursorChar:"";
substr(0,numChars)+cursor;
} else {
substr(0, numChars);
	
	
}
