### ISSUE TITLE
Changing size of the structure

### ISSUE THREAD

**Issue by SEGA201** [Rainbox-dev/DuAEF_Duik#691] opened 2020-06-15 07:08 UTC
**Describe the bug**
When you try to change the size of structures in the structure edit panel, duik completely freezes and does not react to anything.
I tried to turn off duik and run it back, it gives me an error. 
I have to restart After Effects to make it work again.
Most intresting stuff is that all of my versions of duik freezes(i'm using 3 of them at the same time).

**To Reproduce**
1. Select structures 
2. Open structure edit panel
3. Click on size button to change it
4. And it stuck

**Error description, if any**
Unable to execute script at line 3718. Expected: ] - null is not an object.

**Expected behavior**

**Screenshots**
![1171](https://user-images.githubusercontent.com/56382023/84627716-0e171800-aef0-11ea-9f6b-ec2e61616efc.PNG)

**System (please complete the following information):**
OS: Windows 10
Version of After Effects: CC2018
Version of Duik: 16.2.13, 16.1.3 and 15.52

**Comment by Nico-Duduf** [comment] 2020-06-15 08:40
Thanks, I'll have a look at that.

Just one question though, are you trying to change the size before or after running the auto-rig

**Comment by SEGA201** [comment] 2020-06-15 08:42
In both cases i get the same error.

**Comment by Nico-Duduf** [comment] 2020-06-21 16:19
Actually, I can reproduce only after having ran the auto-rig. The issue is fixed in 16.2.14 available in a few days, but note that anyway, you can't change the appearance of the Structures after having used the auto-rig with them, as the "bake appearance" option of the auto-rig is checked by default.
Of course you can change the option, but it improves a lot the performance, so I recommend to keep it checked.

**Closed by Nico-Duduf** 2020-06-21 16:19 UTC
Labels: Bug
