### ISSUE TITLE
Creating Structures from selections does not work

### ISSUE THREAD

**Issue by planetfrenzy** [Rainbox-dev/DuAEF_Duik#519] opened 2019-09-18 21:45 UTC
**Describe the bug**
In your video tutorial "The Official Character Rigging course with Duik Bassel", the 3rd video under "structures" topic, "With a Selection", a process is described whereby a structure can be created from layers, or puppet pins and those layers/puppet pins would be AUTOMATICALLY PARENTED (obviously this is a huge time saver). This does not happen. A structure gets created but I must parent by hand still.
Does this feature really work? I am truly frustrated with the time I've spent trying I hate to say :(. 
Look forward,
MP
I have faith though!
**To Reproduce**
1. 
2. 
3. 

**Error description, if any**
File: 
Line number:
Error message: 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47117626/65188270-077c7280-da3c-11e9-8375-ee410c4f3aea.png)

**System (please complete the following information):**
 - OS: 
 - Version of After Effects: 
 - Version of Duik: 

**Additional context**

**Comment by planetfrenzy** [comment] 2019-09-18 21:46
After Effects 2019, newly downloaded version of DUIK.

**Comment by Nico-Duduf** [comment] 2019-10-09 15:41
Are the Structures correctly moved to the selection?

if this is the case and the issue is that they're just not parented, do you have the option for auto link checked in the edit panel of the structures?

See this screenshot:
![image](https://user-images.githubusercontent.com/8526542/66496918-f8796500-eabb-11e9-9767-f436df9738ea.png)

**Comment by planetfrenzy** [comment] 2019-10-09 16:28
Aha! Ça marche!

This is great. Thank you so much, I’ve been looking forward to
running headlong into this application.

All the Best,
Mark Parenteau

----- Original Message -----
From:
 "Rainbox-dev/DuAEF_Duik"
<reply@reply.github.com>

To:
"Rainbox-dev/DuAEF_Duik" <DuAEF_Duik@noreply.github.com>
Cc:
"planetfrenzy" <mark@planetfrenzy.com>, "Author"
<author@noreply.github.com>
Sent:
Wed, 09 Oct 2019 08:41:21 -0700
Subject:
Re: [Rainbox-dev/DuAEF_Duik] Creating Structures from selections does
not work (#519)

	Are the Structures correctly moved to the selection? 

	if this is the case and the issue is that they're just not parented,
do you have the option for auto link checked in the edit panel of the
structures? 

	See this screenshot:
 [1] 

	—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [2], or mute the
thread [3]. 

Links:
------
[1]
https://user-images.githubusercontent.com/8526542/66496918-f8796500-eabb-11e9-9767-f436df9738ea.png
[2]
https://github.com/Rainbox-dev/DuAEF_Duik/issues/519?email_source=notifications&amp;email_token=ALHPKOVFALQ263VZZ2P2MOTQNX3SDA5CNFSM4IYEB2LKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAYKPAA#issuecomment-540059520
[3]

**Closed** 2019-10-09 16:31 UTC
Labels: Bug, Question
