### ISSUE TITLE
Wiggle effect bug

### ISSUE THREAD

**Issue by SEGA201** [Rainbox-dev/DuAEF_Duik#534] opened 2019-10-10 06:36 UTC
**Describe the bug**
Can't create a wiggle effect on any property (Rotation, Position etc.). By pressing "Wiggle" button in Duik Bassel.1, it's creates an effect in Effect Controls in layer, but no expresions been created in property (Rotation, Position etc.), so the effect does not working.

**To Reproduce**
1. Click on desirable property (Rotation, Position etc.)
2. Click on "Wiggle" button in Duik Bassel.1.
3. Get an "Wiggle" effect in Effect Controls in layer, but no expresions.

**Expected behavior**
To create a "Wiggle" effect by using Duik Bassel.1 and not writing it in expressions by myself.

**Screenshots**
https://cdn1.imggmi.com/uploads/2019/10/10/005c8922900e9f88a5fe95207afbdf4b-full.png

**System (please complete the following information):**
 - OS: Windows 10
 - Version of After Effects: CC 2018
 - Version of Duik: Duik Bassel.1 v16.1.2

**Comment by SEGA201** [comment] 2019-10-10 14:35
Maybe it's just me, or problems of the new version, but by installing version 16.1.0, this bug been removed, but shown some another, and going a little bit farther and installing version 16.0.9, happily to me, totaly removed this bug.
And i haven't find another one yet.

**Comment by Nico-Duduf** [comment] 2019-10-11 11:50
I can't reproduce the bug here, it works correctly.
But I've made other changes since your report, so maybe these changes fixed it.
A new version 16.1.3 will be released today, let me know if it works with it on your side!

**Closed** 2020-02-25 18:44 UTC
Labels: Bug, Question, Stand by
